# Generated by Django 3.2.9 on 2021-11-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('vboost_1', models.FloatField()),
                ('vboost_2', models.FloatField()),
                ('vboost_3', models.FloatField()),
                ('battery_volt', models.FloatField()),
                ('current_in_1', models.FloatField()),
                ('current_in_2', models.FloatField()),
                ('current_in_3', models.FloatField()),
                ('system_current', models.FloatField()),
            ],
        ),
    ]
