# Generated by Django 3.2.9 on 2021-11-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapacket',
            old_name='wdt_time_and',
            new_name='wdt_time_gnd',
        ),
    ]
