# Generated by Django 3.2.9 on 2021-11-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapacket',
            name='battery_volt',
        ),
        migrations.RemoveField(
            model_name='datapacket',
            name='current_in_1',
        ),
        migrations.RemoveField(
            model_name='datapacket',
            name='current_in_2',
        ),
        migrations.RemoveField(
            model_name='datapacket',
            name='current_in_3',
        ),
        migrations.RemoveField(
            model_name='datapacket',
            name='system_current',
        ),
    ]
