# Generated by Django 3.2.9 on 2021-11-21 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_wdt_time_and_datapacket_wdt_time_gnd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapacket',
            old_name='boot_cause',
            new_name='bootcause',
        ),
    ]
