from django.db import models


class DataPacket(models.Model):
  """
  defines the fields for the Datapacket sqlite table 
  """
  time = models.FloatField()
  vboost_1 = models.FloatField()
  vboost_2 = models.FloatField()
  vboost_3 = models.FloatField()
  # battery_volt = models.FloatField()
  # current_in_1 = models.FloatField()
  # current_in_2 = models.FloatField()
  # current_in_3 = models.FloatField()
  # system_current = models.FloatField()
  # reserved1 = models.FloatField()
  # curout1 = models.FloatField()
  # curout2 = models.FloatField()
  # curout3 = models.FloatField()
  # curout4 = models.FloatField()
  # curout5 = models.FloatField()
  # curout6 = models.FloatField()
  # outputs = models.FloatField()
  # latchups = models.FloatField()
  # latchups4 = models.FloatField()
  # latchups5 = models.FloatField()
  # latchups6 = models.FloatField()
  # wdt_time_left_I2C = models.FloatField()
  # wdt_time_left_GND = models.FloatField()
  # wdt_counts_I2C = models.FloatField()
  # wdt_counts_GND = models.FloatField()
  # gom_boots = models.FloatField()
  # gom_battmode = models.FloatField()
  # hk_temp_1 = models.FloatField()
  # hk_temp_2 = models.FloatField()
  # hk_temp_3 = models.FloatField()
  # hk_temp_4 = models.FloatField()
  # gom_ppt_mode = models.FloatField()
  # reserved2 = models.FloatField()
  # rtc_time = models.FloatField()
  # rpi_cpu = models.FloatField()
  # rpi_ram = models.FloatField()
  # rpi_dsk = models.FloatField()
  # rpi_temp = models.FloatField()
  # rpi_boot = models.FloatField()
  # rpi_uptime = models.FloatField()
  # gyrox = models.FloatField()
  # gyroz = models.FloatField()
  # accx = models.FloatField()
  # accy = models.FloatField()
  # accz = models.FloatField()
  # magx = models.FloatField()
  # magy = models.FloatField()
  # magz = models.FloatField()
  # gyro_temp = models.FloatField()
  # thermocouple_temp = models.FloatField()
  # prop_tank_pressure = models.FloatField()
  # position_x = models.FloatField()
  # position_y = models.FloatField()
  # position_z = models.FloatField()
  # att_1 = models.FloatField()
  # att_2 = models.FloatField()
  # att_3 = models.FloatField()
  # att_4 = models.FloatField()